devcontainers/cli

README.md

Updating the try out instructions. Mentioning the dependency on Python and C/C++.

Try out package

---

.vscode/settings.json
src/spec-common/commonUtils.ts
src/spec-common/proc.ts
src/spec-common/shellServer.ts
src/spec-configuration/configuration.ts
src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-node/containerFeatures.ts
src/spec-node/devContainers.ts
src/spec-node/devContainersSpecCLI.ts
src/spec-node/dockerCompose.ts
src/spec-node/singleContainer.ts
src/spec-node/utils.ts
src/spec-shutdown/dockerUtils.ts
src/spec-utils/event.ts
src/spec-utils/log.ts
src/test/container-features/generateFeaturesConfig.offline.test.ts
src/test/container-features/generateFeaturesConfig.online.test.ts
src/test/container-features/helpers.offline.test.ts

Apply the repo-configured editor formatting to all TS files and configure formatOnSave to reduce formatting diffs in future PRs

Format .ts files and configure formatOnSave

---

src/spec-node/containerFeatures.ts
src/spec-node/dockerCompose.ts

Refactor the `startContainer` method in `dockerCompose.ts` to bring the build and extend steps closer together ready for combining into a single, multi-stage build
Future steps:
- add tests for "Clone in Volume" and "Codespaces" code paths (container already exists and persisted files do/don't exist)
- combine build and extend and update to multi-stage build

Refactor startContainer for docker-compose

---

src/spec-node/dockerCompose.ts
src/test/cli.test.ts
src/test/configs/compose-Dockerfile-alpine/.devcontainer/Dockerfile
src/test/configs/compose-Dockerfile-alpine/.devcontainer/devcontainer.json
src/test/configs/compose-Dockerfile-alpine/.devcontainer/docker-compose.yml
src/test/configs/compose-Dockerfile-with-target/.devcontainer/devcontainer.json
src/test/configs/dockerfile-with-target/.devcontainer.json

- Add post*Command tests
- Simplify test output on failure
- Prevent recreate if container exists

Add --no-recreate for existing container

---

src/spec-common/cliHost.ts
src/spec-common/commonUtils.ts
src/spec-node/utils.ts
src/test/container-features/generateFeaturesConfig.offline.test.ts
src/test/container-features/generateFeaturesConfig.online.test.ts

Fixes https://github.com/microsoft/vscode-remote-release/issues/6913.

Fall back to 'id -u -n' (microsoft/vscode-remote-release#6913)

---

src/spec-node/devContainersSpecCLI.ts
src/spec-node/dockerCompose.ts

Fixing https://github.com/microsoft/vscode-remote-release/issues/7047

Updated default image name (microsoft/vscode-remote-release#7047)

---

example-usage/tool-openvscode-server/start.sh
example-usage/tool-vim-via-ssh/start.sh
example-usage/tool-vscode-server/start.sh

Missed a couple spots during a refactor

Fix bug with path in example-usage

---

example-usage/README.md
example-usage/tool-openvscode-server/server/init-openvscode-server.sh
example-usage/tool-openvscode-server/start.sh
example-usage/tool-vim-via-ssh/start.sh
example-usage/tool-vscode-server/server/init-vscode-server.sh
example-usage/tool-vscode-server/start.sh
example-usage/workspace/.devcontainer/devcontainer.json

In this case, VS Code extensions and settings.

Improve CLI examples to illustrate application of tool specific settings

---

src/spec-node/containerFeatures.ts
src/test/container-features/configs/image-with-v1-features-node-python-local-cache/.devcontainer.json
src/test/container-features/e2e.test.ts
src/test/testUtils.ts

fixes https://github.com/devcontainers/cli/issues/131

Emit newline in between ENV statements in features dockerfile (v1 only)

---

package.json

pick up https://github.com/devcontainers/cli/issues/131 in the latest npm release

update package.json to 0.12.1

---

src/spec-common/injectHeadless.ts
src/spec-node/devContainersSpecCLI.ts
src/spec-node/utils.ts
src/test/cli.test.ts
src/test/configs/image/.devcontainer.json
src/test/variableSubstitution.test.ts

Fixes microsoft/vscode-remote-release#7121.

Apply containerEnv on entire config

---

src/spec-node/containerFeatures.ts
src/spec-node/devContainers.ts
src/spec-node/dockerCompose.ts
src/spec-node/featuresCLI/testCommandImpl.ts
src/spec-node/utils.ts

https://github.com/microsoft/vscode-remote-release/issues/7068

Fix: multiple users /tmp/docker-compose permission denied

---

src/spec-node/collectionCommonUtils/packageCommandImpl.ts
src/spec-node/featuresCLI/testCommandImpl.ts
src/test/container-features/example-v2-features-sets/simple/src/color/devcontainer-feature.json
src/test/container-templates/example-templates-sets/simple/src/cpp/devcontainer-template.json

closes https://github.com/devcontainers/cli/issues/214

Tolerate comments in json when packaging

---

package.json
src/spec-configuration/containerCollectionsOCI.ts
src/spec-configuration/containerFeaturesOCI.ts
src/spec-configuration/containerTemplatesOCI.ts
src/test/container-features/containerFeaturesOCI.test.ts
src/test/container-templates/containerTemplatesOCI.test.ts

Use the existing OCI implementation to fetch Templates.

Wire up fetching a Template from an OCI registry

---

src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-node/imageMetadata.ts
src/test/imageMetadata.test.ts

Fixes microsoft/vscode-remote-release#7368.

Last mount source wins (microsoft/vscode-remote-release#7368)

---

src/spec-node/dockerfileUtils.ts
src/spec-node/imageMetadata.ts
src/spec-node/utils.ts
src/test/dockerfileUtils.test.ts

Fixes microsoft/vscode-remote-release#7303.

Handle ENV (microsoft/vscode-remote-release#7303)

---

src/spec-node/imageMetadata.ts
src/test/imageMetadata.test.ts

Apply current configuration (#252)

---

src/spec-node/dockerfileUtils.ts
src/test/dockerfileUtils.test.ts

Fixes microsoft/vscode-remote-release#7323

Handle quoted base image (microsoft/vscode-remote-release#7323)

---

src/spec-configuration/containerFeaturesConfiguration.ts
src/test/cli.build.test.ts
src/test/configs/compose-image-without-features-minimal/.devcontainer/devcontainer.json
src/test/configs/compose-image-without-features-minimal/.devcontainer/docker-compose.yml

microsoft/vscode-remote-release#7305

Skip features code path without features (microsoft/vscode-remote-release#7305)

---

src/spec-configuration/containerFeaturesConfiguration.ts

chmod as root (#153)

---

docs/features/test.md
src/test/container-features/example-v2-features-sets/simple/test/_global/scenarios.json

Repo was renamed and OCI Feature republished
See: https://github.com/devcontainers/feature-starter

change 'feature-template' -> 'feature-starter'

---

src/spec-node/containerFeatures.ts
src/spec-node/devContainersSpecCLI.ts
src/spec-node/dockerCompose.ts
src/spec-node/imageMetadata.ts
src/spec-node/singleContainer.ts
src/test/configs/compose-image-without-features-minimal/.devcontainer/devcontainer.json
src/test/configs/compose-image-without-features-minimal/.devcontainer/docker-compose.yml
src/test/imageMetadata.test.ts

Fixes microsoft/vscode-remote-release#7378.

Avoid image build (microsoft/vscode-remote-release#7378)

---

src/spec-node/dockerfileUtils.ts
src/test/dockerfileUtils.test.ts

Fixes microsoft/vscode-remote-release#7493

Optional = (microsoft/vscode-remote-release#7493)

---

.github/workflows/dev-containers.yml
.gitignore
.vscode/tasks.json
esbuild.js
package.json
src/test/cli.exec.base.ts
src/test/dockerUtils.test.ts
tsconfig.base.json

Implements devcontainers/cli#279

Bundle CLI for NPM package (devcontainers/cli#279)

---

src/spec-node/containerFeatures.ts

Help track down microsoft/vscode-remote-release#7382

Surface first error (microsoft/vscode-remote-release#7382)

---

src/spec-node/containerFeatures.ts
src/test/configs/compose-image-without-features-minimal/.devcontainer/devcontainer.json
src/test/configs/image/.devcontainer.json
src/test/imageMetadata.test.ts

Include config (#299)

---

ThirdPartyNotices.txt
package.json
yarn.lock

Also update ThirdPartyNotices.txt.

Chalk 5 is ESM only

---

src/spec-configuration/containerCollectionsOCI.ts
src/spec-configuration/containerCollectionsOCIPush.ts
src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-configuration/containerFeaturesOCI.ts
src/spec-configuration/containerTemplatesOCI.ts
src/spec-node/collectionCommonUtils/publishCommandImpl.ts
src/spec-node/featuresCLI/infoManifest.ts
src/spec-node/featuresCLI/infoTags.ts
src/spec-node/featuresCLI/publish.ts
src/spec-node/templatesCLI/apply.ts
src/spec-node/templatesCLI/publish.ts
src/spec-node/utils.ts
src/test/container-features/containerFeaturesOCI.test.ts
src/test/container-features/containerFeaturesOCIPush.test.ts
src/test/container-features/featureHelpers.test.ts
src/test/container-features/featuresCLICommands.test.ts
src/test/container-templates/containerTemplatesOCI.test.ts

Combines arguments into a single `param` object that we can pass around instead.

clean up arguments in Features code

---

CHANGELOG.md
package.json

Release '0.27.0'

---

docs/templates/publish.md

ref: https://github.com/microsoft/vscode-dev-containers/pull/1238

Add docs for `devcontainer templates publish`

---

package.json

https://github.com/devcontainers/cli/commit/8a7412a22c9459d723e9370eb38dd7eac589fa1f updates the changelog

increase package.json to v0.32.0

---

package.json
src/spec-configuration/containerFeaturesConfiguration.ts
src/test/container-features/featureHelpers.test.ts

Transform maven, gradle and jupyterlab usages to their features v2 counterparts

---

src/spec-node/devContainersSpecCLI.ts
src/test/cli.build.test.ts
src/test/cli.exec.base.ts
src/test/cli.test.ts
src/test/cli.up.test.ts
src/test/configs/dockerfile-without-features/.devcontainer/subfolder/Dockerfile
src/test/configs/dockerfile-without-features/.devcontainer/subfolder/devcontainer.json

microsoft/vscode-remote-release#8068

Add --config to build command

---

src/spec-node/configContainer.ts
src/spec-node/utils.ts

For clarity, rename the command the executes InitializeCommand on the host.

change 'runUserCommand(...)' to 'runInitializeCommand(...)'

---

src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-configuration/lockfile.ts

Keep existing lockfile updated

---

src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-configuration/controlManifest.ts
src/spec-configuration/featureAdvisories.ts
src/spec-node/containerFeatures.ts
src/spec-node/devContainersSpecCLI.ts
src/test/container-features/featureAdvisories.test.ts
src/test/container-features/generateFeaturesConfig.test.ts
src/test/disallowedFeatures.test.ts

We can remove the hard-coded test advisory after its PR went in.

Log feature advisories

---

src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-node/containerFeatures.ts
src/spec-node/imageMetadata.ts
src/test/container-features/example-v1-features-sets/simple/devcontainer-features.json
src/test/container-features/generateFeaturesConfig.test.ts

https://github.com/devcontainers/cli/issues/532

Fix: containerEnv values with spaces

---

src/spec-configuration/containerFeaturesConfiguration.ts

Fixes microsoft/vscode-remote-release#8434

Log fetched feature version

---

src/spec-node/dockerfileUtils.ts
src/test/dockerfileUtils.test.ts

Fixes microsoft/vscode-remote-release#6850

Case-insensitive instructions

---

src/spec-common/injectHeadless.ts

https://github.com/microsoft/vscode-remote-release/issues/2957

Use getent passwd

---

src/spec-configuration/lockfile.ts
src/test/container-features/configs/lockfile-dependson/.devcontainer.json
src/test/container-features/configs/lockfile-dependson/.gitignore
src/test/container-features/configs/lockfile-dependson/expected.devcontainer-lock.json
src/test/container-features/lockfile.test.ts

https://github.com/devcontainers/cli/issues/564

Record feature dependencies in the lockfile

---

src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-configuration/containerFeaturesOrder.ts
src/spec-configuration/lockfile.ts
src/spec-node/featuresCLI/info.ts
src/spec-node/featuresCLI/resolveDependencies.ts
src/test/container-features/configs/lockfile-dependson/.devcontainer.json
src/test/container-features/configs/lockfile-dependson/expected.devcontainer-lock.json
src/test/container-features/configs/lockfile-oci-integrity/.devcontainer-lock.json
src/test/container-features/configs/lockfile-oci-integrity/.devcontainer.json
src/test/container-features/configs/lockfile-tarball-integrity/.devcontainer-lock.json
src/test/container-features/configs/lockfile-tarball-integrity/.devcontainer.json
src/test/container-features/configs/lockfile/expected.devcontainer-lock.json
src/test/container-features/lockfile.test.ts

https://github.com/devcontainers/spec/issues/236

Record features referenced by tarball URI

---

src/spec-common/commonUtils.ts
src/spec-common/injectHeadless.ts
src/spec-shutdown/dockerUtils.ts

Allocate pty

---

scripts/updateUID.Dockerfile
src/test/configs/updateUID/.devcontainer.json
src/test/configs/updateUID/Dockerfile
src/test/configs/updateUIDOnly/.devcontainer.json
src/test/configs/updateUIDOnly/Dockerfile
src/test/testUtils.ts
src/test/updateUID.test.ts

https://github.com/microsoft/vscode-remote-release/issues/7284

Update UID only when GID is taken

---

src/spec-configuration/containerFeaturesConfiguration.ts
src/spec-node/containerFeatures.ts
src/spec-node/devContainers.ts
src/spec-node/dockerCompose.ts
src/spec-node/utils.ts
src/spec-shutdown/dockerUtils.ts

Mount build context as shared with buildah

---

src/spec-node/dockerCompose.ts

Fixes microsoft/vscode-remote-release#7305

Adopt additional_contexts in compose

---

src/spec-node/singleContainer.ts

Fixes microsoft/vscode-remote-release#5887

Log `docker start` output

---

src/spec-configuration/configuration.ts
src/spec-node/singleContainer.ts
src/test/cli.build.test.ts
src/test/configs/dockerfile-with-target/.devcontainer.json

Support additional Docker build options

---

src/spec-node/devContainersSpecCLI.ts
src/test/cli.exec.base.ts

Fixes https://github.com/devcontainers/ci/issues/231

Allow empty value for remote env

---

yarn.lock

Fixes some Component Governance issues.

chore: bump dependencies

---

src/spec-configuration/containerFeaturesConfiguration.ts

https://github.com/devcontainers/cli/issues/776

Only use SELinux label for Linux hosts

---

.github/workflows/publish-dev-containers.yml

Required to download artifacts uploaded with v4 of the upload action.

Update to latest download action

---

src/spec-node/containerFeatures.ts
src/spec-node/devContainers.ts
src/spec-node/utils.ts
src/spec-shutdown/dockerUtils.ts

Fixes microsoft/vscode-remote-release#9748

Qualify local image for Podman

---

CHANGELOG.md
package.json
src/spec-node/containerFeatures.ts

microsoft/vscode-remote-release#9748

Check if image name has registry host

---

src/spec-common/dotfiles.ts

Fixes https://github.com/devcontainers/cli/issues/829

Use --depth 1 to make dotfiles install process faster

---

CHANGELOG.md
package.json
src/spec-node/dockerCompose.ts
src/test/cli.up.test.ts
src/test/configs/compose-with-name-and-custom-yaml/.devcontainer/devcontainer.json
src/test/configs/compose-with-name-and-custom-yaml/.devcontainer/docker-compose.yml
src/test/configs/compose-without-name/.devcontainer/devcontainer.json
src/test/configs/compose-without-name/.devcontainer/docker-compose.yml

Fix support for project name attribute

---

CHANGELOG.md

I forgot to include https://github.com/devcontainers/cli/pull/815 in the changelog

Update 0.63.0 CHANGELOG

---

CHANGELOG.md
package.json
src/spec-node/dockerCompose.ts
src/test/cli.up.test.ts
src/test/configs/compose-with-name-using-env-var/.devcontainer/devcontainer.json
src/test/configs/compose-with-name-using-env-var/.devcontainer/docker-compose.yml

Fix project name with env variable

---

CHANGELOG.md
package.json
src/spec-node/devContainersSpecCLI.ts

microsoft/vscode-remote-release#10029

Wait for result to be written

---

src/spec-common/injectHeadless.ts
src/spec-node/devContainersSpecCLI.ts
src/spec-node/dockerCompose.ts
src/spec-node/singleContainer.ts
src/spec-node/utils.ts
src/test/cli.set-up.test.ts
src/test/cli.up.test.ts
src/test/configs/image/.devcontainer.json
src/test/configs/set-up-with-config/devcontainer.json
src/test/configs/set-up-with-metadata/Dockerfile

Fixes microsoft/vscode-remote-release#10033

Fix containerEnv substitution

---

src/spec-node/dockerCompose.ts
src/spec-node/singleContainer.ts
src/spec-node/utils.ts
src/spec-shutdown/dockerUtils.ts
src/test/dockerUtils.test.ts

microsoft/vscode-remote-release#6509

Handle concurrent removal

---

src/spec-configuration/containerTemplatesOCI.ts
src/spec-node/devContainersSpecCLI.ts
src/spec-node/featuresCLI/generateDocs.ts
src/spec-node/featuresCLI/info.ts
src/spec-node/featuresCLI/package.ts
src/spec-node/featuresCLI/publish.ts
src/spec-node/featuresCLI/resolveDependencies.ts
src/spec-node/featuresCLI/test.ts
src/spec-node/templatesCLI/apply.ts
src/spec-node/templatesCLI/generateDocs.ts
src/spec-node/templatesCLI/metadata.ts
src/spec-node/templatesCLI/publish.ts
src/spec-node/upgradeCommand.ts
src/spec-node/utils.ts

Fixes microsoft/vscode-remote-release#10217

Exit with non-zero code on unexpected errors

---

src/spec-shutdown/dockerUtils.ts

microsoft/vscode-remote-release#6509

Increase timeout to 6 seconds (7 attempts)

---

src/spec-node/singleContainer.ts

https://github.com/microsoft/vscode-remote-release/issues/10798

Add Podman options

---

src/spec-node/dockerCompose.ts

https://github.com/microsoft/vscode-remote-release/issues/10691

Restore accidental robustness towards numbers

---

src/spec-node/singleContainer.ts

Fix: --uidmap/--gidmap conflict with --userns
