src/spec-node/containerFeatures.ts, src/spec-node/devContainers.ts, src/spec-node/singleContainer.ts, src/spec-node/utils.ts, src/spec-shutdown/dockerUtils.ts
The `--build-context` switch was only added in 0.8.0.
This PR adds a version check with fallback to alternative build approach.
=> Add buildx version check

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
Add a volume for the container and configure bash to store history on it so that bash history isn't lost across container instances
=> Preserve bash history across instances

src/spec-node/devContainers.ts, src/spec-node/dockerCompose.ts, src/spec-node/utils.ts, src/test/cli.test.ts, src/test/configs/compose-with-features/.devcontainer/Dockerfile, src/test/configs/compose-with-features/.devcontainer/devcontainer.json, src/test/configs/compose-with-features/.devcontainer/docker-compose.yml
Tracking progress towards multi-stage builds  (#10)
- Add a test for docker-compose, with container features
- Remove unused `collapsedFeaturesConfig` return value from `startContainer` function
- Include `composeProjectName` in output when starting a docker-compose dev container (and use that to stop the compose projects in tests)
=> Prep for multi-stage build for docker-compose

src/spec-node/containerFeatures.ts, src/test/container-features/helpers.offline.test.ts
Through experimentation and via the web with out auto-generated `_BUILD_ARG`s, it appears :
`
Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.
`
This transforms the outputted `_BUILD_ARG_..` in an opinionated way.
cc/ @greggroth
=> Sanitize feature input options to be set as `_BUILD_ARG..`

src/spec-node/singleContainer.ts
Fix bug that only allowed `--cache-from` args to be applied when the `devcontainer.json` contained a `build.cacheFrom` entry
=> Enable explicit CacheFrom when no cacheFrom in devcontainer.json

src/spec-node/dockerCompose.ts
Refactor the handling when a container exists but the persisted files do not to handle scenarios such as the build override not existing and needing recreating.
=> Regenerate all overrides as needed if not exist

src/spec-node/containerFeatures.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/singleContainer.ts, src/test/cli.test.ts
It allows to tag the same image more than once.
eg - `devcontainer build --workspace-folder ./ --image-name alpine3 --image-name alpine3.0`
This is mainly needed for multiple tagging of multi-arch images created with `--platform`.
If the cli creates a multi arch image, and if you retag with `docker tag` then the new image ends up using architecture of the current machine for tagging.
Hence, such multi-arch images needs to be tagged during image build else they won't support multi-architecture platform.
=> Build command: Support multiple --image-name parameters 

src/spec-configuration/containerFeaturesConfiguration.ts
Reported in: https://github.com/devcontainers/cli/issues/91
With the refactoring and addition of the devcontainer-feature.json file special values were no longer being saved to be processed at container creation time.
=> Fix for regression in features functionality.

package.json, src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/containerFeaturesOCI.ts, src/spec-node/containerFeatures.ts, src/test/cli.test.ts, src/test/configs/dockerfile-with-v2-oci-features/.devcontainer.json, src/test/configs/dockerfile-with-v2-oci-features/Dockerfile, src/test/configs/invalid-configs/invalid-v1-features/.devcontainer.json, src/test/configs/invalid-configs/invalid-v2-features/.devcontainer.json, src/test/container-features/containerFeaturesOCI.offline.test.ts
Fixes a regression in `github-repo` features following the 'v1' pattern. A previous patch (https://github.com/devcontainers/cli/commit/0c22d279529fe88960a761ae1e6997df0d3462e8) only covered the `local-features` case. This aims to make the patch more generic.
This regression was missed in automated unit testing because parse errors in features were previously not a fatal error.  This PR makes failing to parse a feature fatal to the entire image build.
=> 'v1' features regression

src/test/container-features/containerFeaturesOCI.test.ts
Pins a test feature to an older tag that we won't disturb while testing.
We will only use the `codspace` test repo so long as the official features repo is not open source.  Once we open source that repo, all these tests should be swapped over to that repo for tidiness.
=> fix OCI feature test 

README.md, example-usage/README.md, example-usage/ci-app-build-script/build-application.sh, example-usage/image-build/build-image.sh, example-usage/tool-openvscode-server/server/init-openvscode-server.sh, example-usage/tool-openvscode-server/start.sh, example-usage/tool-vim-via-ssh/server/init-vim.sh, example-usage/tool-vim-via-ssh/start.sh, example-usage/tool-vscode-server/server/init-vscode-server.sh, example-usage/tool-vscode-server/start.sh, example-usage/workspace/.devcontainer/Dockerfile, example-usage/workspace/.devcontainer/devcontainer.json, example-usage/workspace/go.mod, example-usage/workspace/main.go, example-usage/workspace/scripts/execute-app-build.sh
This PR adds in scripts and a README that illustrates how to use the CLI to:
- Inject tools for use inside a development container
- Use a dev container as your CI build environment to build an application (even if it is not deployed as a container)
- Build a container image from a devcontainer.json file that includes dev container features
=> Add more examples of using the CLI

src/spec-node/devContainersSpecCLI.ts
Fixes #114
This uses an epilogue inspired by `npm --help`.
With this proposed change, when executed after being globally installed, `devcontainer --help` will print something like:
```
devcontainer <command>
Commands:
devcontainer up                   Create and run dev container
devcontainer build [path]         Build a dev container image
devcontainer run-user-commands    Run user commands
devcontainer read-configuration   Read configuration
devcontainer features             Features commands
devcontainer exec <cmd> [args..]  Execute a command on a running dev container
Options:
--help     Show help                                                                                         [boolean]
--version  Show version number …
```
=> Print version and install location at the end of `--help`

src/spec-common/variableSubstitution.ts, src/test/variableSubstitution.test.ts
This is related to #50 and might even close it.
=> Implement optional default values in localEnv/containerEnv expansions

src/spec-configuration/configuration.ts, src/spec-configuration/containerFeaturesConfiguration.ts, src/test/container-features/configs/dockerfile-with-v2-local-features-with-dev-container-folder/local-features/localFeatureA/devcontainer-feature.json, src/test/container-features/configs/dockerfile-with-v2-local-features-with-dev-container-folder/local-features/localFeatureB/devcontainer-feature.json, src/test/container-features/configs/dockerfile-with-v2-oci-features/.devcontainer.json, src/test/container-features/e2e.test.ts, src/test/container-features/generateFeaturesConfig.test.ts
Fixes: https://github.com/devcontainers/cli/issues/125
All props from https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#devcontainer-featurejson-properties are now included in processed features. 
Added tests
=> (IMP) bug fix: missing devcontainer-feature properties are now processed in features

src/spec-configuration/containerFeaturesOCI.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/featuresCLI/info.ts
A simple command that uses the local OCI implementation to fetch information on a dev container feature published to an OCI repository.
Today, this command returns all published tags for a given `featureId`.  The output can either be human-formatted (Default), or JSON.
=> `devcontainer features info <..>` command

.devcontainer/devcontainer.json
We prefer using the full OCI reference to the major version of the feature, over the older style syntax (that we are phasing out).
=> use preferred syntax for docker-in-docker feature

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/containerFeatures.ts, src/test/container-features/configs/dockerfile-with-v2-local-features-no-dev-container-folder/.devcontainer.json, src/test/container-features/configs/dockerfile-with-v2-local-features-no-dev-container-folder/local-features/localFeatureA/install.sh, src/test/container-features/configs/dockerfile-with-v2-local-features-with-dev-container-folder/.devcontainer/devcontainer.json, src/test/container-features/configs/dockerfile-with-v2-local-features-with-dev-container-folder/local-features/localFeatureA/install.sh, src/test/container-features/e2e.test.ts
Fixes https://github.com/devcontainers/cli/issues/148
Instead of trying to use `xargs` to parse the .env file, directly source the .env file with `set -a` enabled.
```
-a
When this option is on, the export attribute shall be set for each variable to which an assignment is performed;
```
In the generated Dockerfile, this env file is simply sources with the `.` operator (The most portable/POSIX-y way to source https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot)
=> Properly source feature options

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/containerFeaturesOrder.ts, src/test/container-features/containerFeaturesOrder.test.ts
This PR fixes the bug reported here:
https://github.com/devcontainers/cli/issues/163
It was just a simple typo.
=> Fix typo in 'installsAfter'

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/containerFeaturesOCI.ts, src/spec-node/containerFeatures.ts, src/test/configs/example/.devcontainer.json, src/test/configs/image-with-features/.devcontainer.json, src/test/container-features/configs/dockerfile-with-v2-oci-features/.devcontainer.json, src/test/container-features/e2e.test.ts, src/test/container-features/featureHelpers.test.ts, src/test/container-features/generateFeaturesConfig.test.ts
Add a header to the output logs for each feature that is executed to provide info about the feature
Example:
```
#15 [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/docker-in-docker_2 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh
#15 0.521 ===========================================================================
#15 0.521 Feature       : Docker (Docker-in-Docker)
#15 0.521 Description   : Create child containers *inside* a container, independent from the host's docker instance. Installs Docker extension in the container along with needed CLIs.
#15 0.521 Id            : ghcr.io/devcontainers/features/docker-in-docker
#15 0.521 Version       : 1.0.4
#15 0.521 Documentation : https://github.com/devcontainers/features/tree/main/src/docker-i …
```
=> Improve feature installation logs

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/configContainer.ts, src/spec-node/containerFeatures.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/dockerCompose.ts, src/spec-node/singleContainer.ts, src/test/container-features/generateFeaturesConfig.test.ts
Initial work to enable additional features to be specified via the CLI
=> Add --additional-features option

src/spec-configuration/containerTemplatesConfiguration.ts, src/spec-configuration/containerTemplatesOCI.ts, src/spec-node/collectionCommonUtils/packageCommandImpl.ts, src/test/container-templates/containerTemplatesOCI.test.ts, src/test/container-templates/example-templates-sets/simple/src/cpp/.devcontainer/devcontainer.json, src/test/container-templates/example-templates-sets/simple/src/node-mongo/.devcontainer/devcontainer.json, src/test/container-templates/templatesCLICommands.test.ts
Extends https://github.com/devcontainers/cli/pull/225.  Allows the caller to supply a list of Features and their associated options, and applies them to the template.
_Note:_ a supporting tool should not allow Features that are _already_ a part of the Template to be deselected.  This metadata will be added to the index (containers.dev/static/devcontainer-index.json) to aid supporting tools in conveying that information.
=> Apply Features when applying a Template

src/spec-common/injectHeadless.ts, src/test/cli.exec.base.ts, src/test/configs/dockerfile-with-parallel-commands/.devcontainer.json, src/test/configs/dockerfile-with-parallel-commands/Dockerfile
Implementation of https://github.com/devcontainers/spec/pull/89.
Allow lifecycle scripts to be run in parallel by specifying them as objects.
@chrmarti and I talked through the problem of how to avoid interleaving output from commands running in parallel and landed on holding command output until the command completes and then writing it. Non-object form commands will still stream their output as they're running.
Example `devcontainer.json`:
```jsonc
{
// ...
"postCreateCommand": {
"post-create-command-1": "touch /tmp/postCreateCommand1.testmarker && echo post create command 1",
"post-create-command-2": "touch /tmp/postCreateCommand2.testmarker && echo post create command 2"
},
"postStartCommand": {
"post-start-command-1": "touch /tmp/postStartCommand1.testmarker && echo post start …
```
=> Support running lifecycle scripts in parallel

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerFeaturesOCI.ts, src/spec-configuration/containerTemplatesConfiguration.ts, src/spec-configuration/containerTemplatesOCI.ts, src/test/container-features/containerFeaturesOCI.test.ts, src/test/container-templates/containerTemplatesOCI.test.ts
When applying a template, this change now looks for the associated `devcontainer-template.json` in the received tarball and applies the default values if a user had not overwritten the value.
=> `template apply` - auto-replace template default options if they exist in metadata file

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/containerFeatures.ts, src/spec-node/dockerCompose.ts, src/spec-node/imageMetadata.ts, src/spec-node/singleContainer.ts, src/test/container-features/featureHelpers.test.ts, src/test/container-features/generateFeaturesConfig.test.ts, src/test/imageMetadata.test.ts
=> User env variables for features

example-usage/ci-app-build-script/build-application.sh, example-usage/tool-openvscode-server/server/init-openvscode-server.sh, example-usage/tool-openvscode-server/start.sh, example-usage/tool-vscode-server/server/init-vscode-server.sh, example-usage/tool-vscode-server/start.sh
Takes advantage of the new mergedConfiguration section in config output to simplify the script and pick up image label info.
Also made a minor tweak to properly return the right exit code from the CI example.
=> Update examples to use mergedConfiguration so image labels work

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/containerFeatures.ts
Resolves #153.
Since the underlying problem was that the permissions for features sources became corrupted and invalidated the cache, I added a new build stage that serves only to `COPY` the features sources and `chmod` them to `0600`. This way, by the time the actual work of installing the features is performed the permissions will have been normalized, allowing subsequent runs to use the install layers as cache.
I tested this manually by
1. Building a devcontainer image with this version of the CLI and pushing it to Docker Hub
2. Clearing the buildkit cache (`docker buildx prune -af`)
3. `docker pull`ing the built image back onto my machine from Docker Hub
4. Building the same image with the **release version** of the CLI and a `--cache-from` on the image from Docker Hub, to validate …
=> Normalize feature permissions in an intetermediate stage before copying them to the final container

src/spec-common/cliHost.ts
This is used to forward ssh-agent connection to Git Bash' ssh-agent.
I'm not sure this is the cleanest way to implement this, but I've not found existing library functions that could reduce the amount of code.
I've checked that the forwarding work using a "test" and a pipe server to be able to test this case:
`ssh-add => \\.\pipe\mypipe => test => call connectLocal to forward to Git Bash's ssh-agent socket`
A way to test with VS Code would be better than using a manual test, but I don't how I could integrate it in VS Code.
I've also tried to test the connection to gpg-agent (via the socket file named `S.gpg-agent.ssh`), but I couldn't make it works, despite expected packets are sent to gpg-agent according to wireshark. It seems that something broke on gpg-agent side according to:
- …
=> Handle Cygwin / Git Bash sockets forwarding on Windows

src/spec-node/featuresCLI/testCommandImpl.ts, src/test/container-features/example-v2-features-sets/not-root-remote-user/src/whoisremoteuser/devcontainer-feature.json, src/test/container-features/example-v2-features-sets/not-root-remote-user/src/whoisremoteuser/install.sh, src/test/container-features/example-v2-features-sets/not-root-remote-user/test/whoisremoteuser/different_remote_user.sh, src/test/container-features/example-v2-features-sets/not-root-remote-user/test/whoisremoteuser/scenarios.json, src/test/container-features/example-v2-features-sets/not-root-remote-user/test/whoisremoteuser/test.sh
tracking: https://github.com/devcontainers/cli/issues/139
Previously, if you set 'remoteUser' in a test, the accompanying test
scripts placed into the shared 'workspaceFolder' would not have the
appropriate permission bits set to be executed by the exec user.
This patch ensure that all files in the workspaceFolder can be
read/written/executed by the exec user.
A test is added to validate creating a user and setting 'remoteUser' in
a scenario, and then running a test within that context to validate.
=> [features test cmd] Write tests with a non-root `remoteUser`

.gitignore, build/patch-packagejson.js, package.json
We moved all dependencies but the node-pty native module to devdependencies with the change for bundling (so these don't get installed again when installing from NPM). This also removes them from the 3rd-party notices. This change reverts that part of the change and instead modifies the package.json only when producing the package for NPM.
=> Keep dependencies for 3rd-party notices generator (devcontainers/cli#279)

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/containerFeaturesOCI.ts, src/spec-configuration/containerTemplatesOCI.ts, src/spec-node/collectionCommonUtils/publishCommandImpl.ts, src/spec-node/featuresCLI/info.ts, src/spec-node/featuresCLI/publish.ts, src/spec-node/templatesCLI/publish.ts, src/spec-node/utils.ts, src/test/container-features/containerFeaturesOCI.test.ts, src/test/container-features/containerFeaturesOCIPush.test.ts, src/test/container-features/featuresCLICommands.test.ts
Downcases the identifier input string (context: https://github.com/oras-project/oras/issues/679)
Additionally, be more strict about what the Feature/Template OCI identifiers that we parse.  `getRef()` now returned `undefined` if the parsed components don't match [the regular expressions provided in the OCI distribution spec]( https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests).
Adds new tests to assert this behavior.
NOTE: This isn't perfect yet, but an improvement. Left two `TODO`s inline.
relevant: 
- https://github.com/oras-project/oras/issues/679
- https://github.slack.com/archives/C0431R35H37/p1669045129224189
- https://github.com/devcontainers/action/pull/105
- https://github.com/devcontainers/action/issues/103
=> downcase OCI identifiers and validate input of getRef()

CHANGELOG.md, package.json, src/spec-configuration/containerCollectionsOCIPush.ts, src/spec-utils/httpRequest.ts
Fixes a regression introduced by https://github.com/devcontainers/cli/commit/6f76c9518230915ca256320573c891f2f305c537
Example: https://github.com/codspace/random-features/actions/runs/3568551420/jobs/5997547286
Success run of the `publish` command:
=> v0.25.1 - Fix regression in `requestResolveHeaders`

src/spec-node/collectionCommonUtils/publishCommandImpl.ts, src/spec-node/featuresCLI/package.ts, src/spec-node/featuresCLI/publish.ts, src/spec-node/templatesCLI/publish.ts
setup work for https://github.com/github/codespaces/issues/11247
Emits a JSON object to standard out at the end of a successful `devcontainer features publish` run.  Each Feature is listed and reports the tag(s) that were updated as a result of this publish.  
An empty array `[]` represents publishing being skipped for that Feature (for example if the Feature version was not updated)
=> emit a JSON summary of the result of the `features publish` command

.github/workflows/dev-containers.yml, .gitignore, src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerCollectionsOCIPush.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/featuresCLI/infoManifest.ts, src/spec-node/featuresCLI/infoTags.ts, src/spec-node/utils.ts, src/spec-utils/httpRequest.ts, src/test/container-features/containerFeaturesOCI.test.ts, src/test/container-features/containerFeaturesOCIPush.test.ts
Exercises the `devcontainer features publish` command against the [OCI registry specification's Reference Implementation ](https://hub.docker.com/_/registry), and updates our implementation to more closely follow the specification. 
More specifically, starts a `registry` container (with hardcoded auth generated with htpasswd).
```js
const startRegistryCmd = `docker run -d -p 5000:5000 \
-v ${resolvedTmpPath}/auth.htpasswd:/etc/docker/registry/auth.htpasswd \
-e REGISTRY_AUTH="{htpasswd: {realm: localhost, path: /etc/docker/registry/auth.htpasswd}}" \
--name registry \
registry`;
```
And then executing the following `publish` command against the registry server running on localhost.
```bash
DEVCONTAINERS_OCI_AUTH='localhost:5000|myuser|mypass' ./${cli} features publish --log-level trace -r …
```
=> A more spec-compliant/resilient OCI distribution implementation

.github/workflows/dev-containers.yml, .gitignore, src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerCollectionsOCIPush.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/featuresCLI/infoManifest.ts, src/spec-node/featuresCLI/infoTags.ts, src/spec-node/utils.ts, src/spec-utils/httpRequest.ts, src/test/container-features/containerFeaturesOCI.test.ts, src/test/container-features/containerFeaturesOCIPush.test.ts
The contents of: https://github.com/devcontainers/cli/pull/310
Reverted and remerging to get the `v0.25.3` tag merged in the right order
=> [remerge] A more spec-compliant/resilient OCI distribution implementation

src/spec-configuration/containerCollectionsOCIPush.ts, src/spec-node/collectionCommonUtils/publishCommandImpl.ts, src/spec-node/featuresCLI/publish.ts, src/spec-node/templatesCLI/publish.ts, src/test/container-features/containerFeaturesOCIPush.test.ts, src/test/container-features/featuresCLICommands.test.ts
Adds more detail to the result printed at the of `devcontainer features|templates publish`.  Notably, will now emit the `version` (which will be a subset of `publishVersions`) and the manifest digest of the artifact (a SHA256 hash of the manifest, which includes the contents)).
The `version` is useful for https://github.com/devcontainers/features/issues/113, and the digest seems generally useful to have moving forward.
```json
{
"color": {
"publishedVersions": [
"1",
"1.0",
"1.0.0",
"latest"
],
"digest": "b5d0ae81ff657720ee3656c3c4c0ab3794c78bb9efb1551ebf3068b3a29632b5",
"version": "1.0.0"
},
"hello": {
"publishedVersions": [
"1",
"1.0",
"1.0.0",
"latest"
],
"digest": "ba3755f8fbde068787eeb5a8377d103c983090a481f1e937e0ce60ec8996bd8a",
"version": "1.0.0"
}
}
```
=> add more detail to the output of publish commands

package.json, src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/containerFeaturesOrder.ts, src/spec-node/collectionCommonUtils/packageCommandImpl.ts, src/spec-node/collectionCommonUtils/publishCommandImpl.ts, src/spec-node/featuresCLI/publish.ts, src/spec-node/templatesCLI/publish.ts, src/test/container-features/configs/example-installsAfter/.devcontainer.json, src/test/container-features/configs/example-legacyIds-2/.devcontainer.json, src/test/container-features/configs/example-legacyIds/.devcontainer.json, src/test/container-features/containerFeaturesOCIPush.test.ts, src/test/container-features/example-v2-features-sets/renaming-feature/src/hello/devcontainer-feature.json, src/test/container-features/example-v2-features-sets/renaming-feature/src/hello/install.sh, src/test/container-features/example-v2-features-sets/renaming-feature/src/new-color/devcontainer-feature.json, src/test/container-features/example-v2-features-sets/renaming-feature/src/new-color/install.sh, src/test/container-features/example-v2-features-sets/renaming-feature/src/not-a-feature/not-a-feature.sh, src/test/container-features/featuresCLICommands.test.ts
Spec PR - https://github.com/devcontainers/spec/pull/163
Spec issue - https://github.com/devcontainers/spec/issues/146
Spec PR to update schema - https://github.com/devcontainers/spec/pull/171
Demo 
- Sample Repo: https://github.com/samruddhikhandale/test-legacyIds
- [Commit](https://github.com/samruddhikhandale/test-legacyIds/commit/f78fc43a242e7d23b888585cc483a5a99fdfba7a) which renames the Feature
- Logs 
- new id package: [new-color](https://github.com/samruddhikhandale/test-legacyIds/pkgs/container/test-legacyids%2Fnew-color/60068268?tag=1.0.10)
- legacyId package: [color](https://github.com/samruddhikhandale/test-legacyIds/pkgs/container/test-legacyids%2Fcolor/60068278?tag=1.0.10)
=> Feature: Adds support for renaming with `legacyIds` property

.github/workflows/dev-containers.yml, .github/workflows/test-windows.yml, src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerCollectionsOCIPush.ts, src/spec-configuration/containerFeaturesOCI.ts, src/spec-configuration/containerTemplatesOCI.ts, src/spec-configuration/httpOCIRegistry.ts, src/spec-node/featuresCLI/infoManifest.ts, src/spec-node/utils.ts, src/test/container-features/configs/azure-container-registry/.devcontainer.json, src/test/container-features/containerFeaturesOCIPush.test.ts, src/test/container-features/registryCompatibilityOCI.test.ts
ref: https://github.com/devcontainers/cli/issues/322
Implements the [Docker Registry v2 authentication via central service specification](https://docs.docker.com/registry/spec/auth/token/) to improve compatibility with registry services.  While not officially part of the distribution specification, this specification is widely used by various container registries.  This change has been tested with Azure Container Registry (acr) and GitHub Container Registry (ghcr). 
As outlined in the spec, requests will initially be made to a registry without any authentication.  If authentication is required by the server, a `401` response will be set and the `WWW-Authenticate` header will be set with information on how to exchange for a bearer token for the given resource, as well as which scopes to …
=> Follow Docker Token Authentication Specification

src/spec-node/dockerfileUtils.ts, src/test/dockerfileUtils.test.ts
fixes: #336 
- Add support for parsing variable expressions in `Dockerfile` as mentioned in Dockerfile references: https://docs.docker.com/engine/reference/builder/#environment-replacement
=> fix: handle parsing variable expression in dockerfile

src/spec-configuration/httpOCIRegistry.ts
The condition in:
```
const authScenario = cachedAuthHeader ? 'Cached' : 'NoAuth';
```
was always `true`, since `cachedAuthHeader` was changed from a `string` to a `Record<string,string>` during development.   To log the correct string in the trace, the registry should be used as a key into that record.
=> Clean up trace logging for `requestEnsureAuthenticated` 

src/spec-node/dockerfileUtils.ts
fixes: #360 
- Modified the `argumentExpression` regex to only allow a certain set of values.
=> fix: modify argument regex to only allow certain set of values

src/spec-node/dockerfileUtils.ts, src/test/dockerfileUtils.test.ts
fixes: #355 
- Modify `fromStatement` and `parseFromLine` regex to allow quotes in variable substition `FROM` statement
=> fix: fixed fromStatement parsing to parse quotes in variable expressions

.devcontainer/devcontainer.json, src/spec-configuration/containerFeaturesConfiguration.ts, src/test/container-features/featureHelpers.test.ts
=> Features preamble: Add warnings for Feature renames & deprecation

src/spec-common/commonUtils.ts
This is to avoid picking up some random executable from the cwd. (Aligning with the Dev Containers extension.)
=> Do not fall back to cwd

src/spec-common/injectHeadless.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts
We've seen that user environment prob command often take multiple seconds to run, which slows down the commands
With this PR, the caller of the `up` command or `run-user-commands` command can optionally pass the cache directory name if they would like to use the cache.
If a cache directory name is provided via `--container-session-data-folder` option, user envs will be cached in that directory, and the subsequent invocations will use the cache instead of probing user envs.
=> Cache user env for performance improvement

src/spec-common/variableSubstitution.ts, src/spec-configuration/configuration.ts, src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/featuresCLI/testCommandImpl.ts, src/spec-node/imageMetadata.ts, src/spec-node/singleContainer.ts, src/test/cli.set-up.test.ts, src/test/configs/set-up-with-config/devcontainer.json, src/test/configs/set-up-with-metadata/Dockerfile
The additional `set-up` command will allow the Dev Containers extension to use the CLI for attaching to an existing container.
The commands `run-user-commands`, `read-configuration` and `exec` also needed changes to support running without a workspace folder and without a config file.
microsoft/vscode-remote-release#7872
=> Add set-up command

src/spec-common/cliHost.ts, src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/httpOCIRegistry.ts, src/spec-node/utils.ts, src/test/dockerUtils.test.ts
This fixes two failing tests `inspect image in docker.io` and `inspect image in mcr.microsoft.com` that began failing on `main`.
The fix is to implement parsing the image index media type,
https://github.com/opencontainers/image-spec/blob/main/image-index.md.  Before this change, something had changed on the dockerhub/mcr side to reject the Accept header we had been sending and expecting as a response:
Note that Features/Templates are uneffected since we have our own mediaTypes and expected format.
=> [oci] Support querying registries that Accept `application/vnd.oci.image.index.v1+json`

docs/templates/apply.md
Documenting the discussion at https://github.com/devcontainers/spec/issues/71#issuecomment-1409453050
=> Docs for `templates apply` command

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/containerFeatures.ts, src/spec-node/imageMetadata.ts, src/test/cli.build.test.ts, src/test/cli.up.test.ts, src/test/configs/image-metadata-containerEnv/.devcontainer/devcontainer.json
Fixes - https://github.com/devcontainers/cli/issues/381
=> Bug fix: Merge metadata logic for containerEnv - devcontainer build

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/containerFeatures.ts, src/test/container-features/generateFeaturesConfig.test.ts
This PR incrementally copies each feature's contents near the layer they're installed, so rebuilds of a devcontainer take full advantage of the build cache.
To illustrate the behavior I built a devcontainer, edited the source of the last feature in the image, then rebuilt it again. With the public `devcontainer` CLI, the image rebuilds all features even though only the last one changed. With this PR, the second build used the layer cache and started from the layer of the changed feature.
* [build-1-old.log](https://gist.github.com/trxcllnt/8b2ff12f29a434e4d4ff2b45cb2fa823#file-build-1-old-log) (`1m31.803s`)
* [build-2-old.log](https://gist.github.com/trxcllnt/8b2ff12f29a434e4d4ff2b45cb2fa823#file-build-2-old-log) (`1m29.621s`)
* [build-1-new.log](https://gist.github.com/trxcllnt/8b2ff12f29 …
=> Incrementally copy features near the layer they're installed

src/spec-node/configContainer.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/singleContainer.ts, src/spec-node/utils.ts
This is to distinguish containers built from the same workspace folder, but with different devcontainer.json files.
Codespaces and the Dev Containers extension always pass in the label to be used, this change does not change their behavior. This change is to replicate the Dev Containers extension's labels here, so they match when the OSS CLI is used standalone.
Codespaces has only one dev container per Docker daemon (the scope of labels) and should not be affected by these considerations.
=> Add label for config file

src/spec-node/featuresCLI/testCommandImpl.ts
Addresses - https://github.com/devcontainers/cli/issues/413
=> Fix -`devcontainer feature test` cmd should fail with non-zero exit code if Feature's sub-folder does not exist

src/spec-node/utils.ts
Over the last ~month Codespaces has been seeing a non-negligible amount of creation failures due to timing out or 5XX errors when pulling from a registry.
Example log seen today:
```
[2023-03-01 22:16:05.063 StartEnvironment I] {"type":"text","level":2,"timestamp":1677708965063,"text":"Error fetching image details: No manifest found for mcr.microsoft.com/devcontainers/miniconda:0-3."}
[2023-03-01 22:16:05.063 StartEnvironment I] {"type":"start","level":2,"timestamp":1677708965063,"text":"Run: docker pull mcr.microsoft.com/devcontainers/miniconda:0-3"}
[2023-03-01 22:16:05.354 StartEnvironment I] {"type":"raw","level":2,"timestamp":1677708965354,"text":"0-3: Pulling from devcontainers/miniconda\r\n"}
[2023-03-01 22:16:07.877 StartEnvironment I] …
```
=> Retry docker pull

docs/features/test.md
Just added a single word 'shell' to markdown to enable syntax highlighting. For comparison...
With ("shell" in markdown):
```shell
#!/bin/bash
set -e
source dev-container-features-test-lib
check "Oryx version" oryx --version
check "Dotnet is not removed if it is not installed by the Oryx Feature" dotnet --version
...
```
Without:
```
#!/bin/bash
set -e
source dev-container-features-test-lib
check "Oryx version" oryx --version
check "Dotnet is not removed if it is not installed by the Oryx Feature" dotnet --version
...
```
Note: If you're not noticing the difference, it's more apparent on dark themes
=> Doc: add shell highlighting to markdown

src/spec-configuration/httpOCIRegistry.ts
ref: https://github.com/devcontainers/cli/issues/434
Use the `identitytoken` added to the standard `~/.docker/config.json` by some tools 
Notably, the result of `az acr login -n <REGISTRY>` command writes the `identitytoken` property, which is expected to be used as a refresh_token.  See the following capture from how oras performs this exchange.
This may be more useful generally, but the only registry we've encountered that expects this is the Azure Container Registry.
Below demonstrates fetching a Feature's manifest by using the auth outputted by `az acr login`.
In an example project:
=> [oci registry impl] Support `az acr login -n <REGISTRY>`

CHANGELOG.md, package.json, src/spec-common/injectHeadless.ts, src/spec-node/containerFeatures.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/featuresCLI/testCommandImpl.ts, src/spec-node/imageMetadata.ts, src/test/configs/compose-Dockerfile-with-features/.devcontainer/devcontainer.json, src/test/configs/compose-Dockerfile-without-features/.devcontainer/devcontainer.json, src/test/configs/compose-image-with-features/.devcontainer/devcontainer.json, src/test/configs/compose-image-without-features-minimal/.devcontainer/devcontainer.json, src/test/configs/dockerfile-without-features/.devcontainer.json, src/test/configs/dockerfile-without-features/Dockerfile, src/test/configs/image-with-features/.devcontainer.json, src/test/configs/image/.devcontainer.json, src/test/imageMetadata.test.ts
Ability to skip storing remoteEnv from devcontainer config on container metadata label, by using the new option `skip-persisting-remote-env-from-config` for the `up` command.
This will help users to avoid putting sensitive variables/secrets on the image label.
=> Ability to skip storing remoteEnv from devcontainer config on container metadata label

src/spec-configuration/httpOCIRegistry.ts
This adds the ability to retrieve registry credentials from a credential helper specified in `credHelpers` or `credsStore` inside ~/.docker/config.json.
=> Add support for Docker credential helpers

src/spec-configuration/httpOCIRegistry.ts
closes https://github.com/devcontainers/cli/issues/477
As reported, ensures that `Object.keys()` is not passed null or undefined.  
NOTE: This change also includes a couple formatting changes when running the auto formatter in VS Code.
=> null coalesce when detecting docker cred helpers

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerFeaturesConfiguration.ts, src/test/container-features/configs/dockerfile-with-v2-oci-features/.devcontainer.json, src/test/container-features/containerFeaturesOCI.test.ts, src/test/container-features/containerFeaturesOrder.test.ts, src/test/container-features/featureHelpers.test.ts, src/test/imageMetadata.test.ts
ref: https://github.com/devcontainers/cli/issues/479
Previously, all Features and Templates resolved a digest and associated manifest by tag.  This change also allow resolving the Feature or Template by sha256 digest directly. 
Eg: 
```json
{
"features": {
"ghcr.io/devcontainers/features/git-lfs@sha256:9e0b6df853ec932203945b76b9cfa7470ebd1f8bd765484027608581f9cf8a77": {}
}
}
```
=> Fetch Features/Templates by digest

.github/workflows/dev-containers.yml, src/spec-configuration/httpOCIRegistry.ts, src/test/container-features/configs/azure-container-registry/.devcontainer.json, src/test/container-features/configs/registry-compatibility/azure-anonymous/.devcontainer.json, src/test/container-features/configs/registry-compatibility/azure-registry-scoped/.devcontainer.json, src/test/container-features/configs/registry-compatibility/github-anonymous/.devcontainer.json, src/test/container-features/configs/registry-compatibility/github-private/.devcontainer.json, src/test/container-features/containerFeaturesOCI.test.ts, src/test/container-features/generateFeaturesConfig.test.ts, src/test/container-features/registryCompatibilityOCI.test.ts, src/test/testUtils.ts
related: https://github.com/devcontainers/cli/issues/473, #468 
Changes here are primarily around re-structuring the different auth strategies to rely more on the standard docker auth strategies (docker config file and docker credential helper), and less on the registry-specific strategies that previously held higher precedence.
The precedence order is now (encoded in [`getCredential(...)`](https://github.com/devcontainers/cli/blob/4fde394ac16df1061b731d2d2f226850277cbce2/src/spec-configuration/httpOCIRegistry.ts#L147):
- parsed out of a special `DEVCONTAINERS_OCI_AUTH` environment variable
- Read from a docker credential helper indicated in config
- Read from a docker cred store indicated in config (https://docs.docker.com/engine/reference/commandline/login/#credentials-store)
- Read …
=> Add regression testing and reorganize auth precedence levels `httpOCIRegistry`

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/containerFeaturesOCI.ts, src/spec-configuration/containerTemplatesOCI.ts, src/spec-configuration/lockfile.ts, src/spec-node/containerFeatures.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/utils.ts, src/test/container-features/configs/lockfile-frozen/.devcontainer-lock.json, src/test/container-features/configs/lockfile-frozen/.devcontainer.json, src/test/container-features/configs/lockfile-outdated/.devcontainer.json, src/test/container-features/configs/lockfile-outdated/.gitignore, src/test/container-features/configs/lockfile-outdated/expected.devcontainer-lock.json, src/test/container-features/configs/lockfile-outdated/original.devcontainer-lock.json, src/test/container-features/configs/lockfile/.devcontainer.json, src/test/container-features/configs/lockfile/.gitignore, src/test/container-features/configs/lockfile/expected.devcontainer-lock.json, src/test/container-features/containerFeaturesOCI.test.ts, src/test/container-features/containerFeaturesOrder.test.ts, src/test/container-features/e2e.test.ts, src/test/container-features/featureHelpers.test.ts, src/test/container-features/lockfile.test.ts, src/test/imageMetadata.test.ts
https://github.com/microsoft/vscode-remote-release/issues/8330
=> Experimental lockfile

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerFeaturesOCI.ts
Follow up https://github.com/devcontainers/cli/pull/495.
=> Improve readablility

src/spec-configuration/containerCollectionsOCIPush.ts, src/spec-configuration/httpOCIRegistry.ts, src/test/container-features/containerFeaturesOCIPush.test.ts
This change updates the output of the `devcontainer features publish` command to include the hashing algorithm (`sha256:`) at the beginning of the digest in the command output.  This simply makes it more consistent with how a user would pin to digest.
=> Consistent usage of digest

src/spec-common/commonUtils.ts, src/spec-common/injectHeadless.ts, src/spec-node/utils.ts, src/test/cli.exec.base.ts, src/test/configs/image-with-parallel-initialize-command/.devcontainer.json
refs: https://github.com/microsoft/vscode-remote-release/issues/7765, https://github.com/devcontainers/spec/issues/168, https://github.slack.com/archives/C0431R35H37/p1683554998695899
Aligns the `initializeCommand` lifecycle hook with the other hooks, allow for the 'object notation', running each provided (and named) command in parallel with one another.
For logging, the behavior is mirrored for the other lifecycle hooks, _not_ continuously streaming the output from each parallel hook, but instead holding the output until the end (otherwise, output will be interleaved and hard to follow).  See the demo below for an illustration of this.
https://user-images.githubusercontent.com/23246594/236972162-860377bb-0337-487b-9dd9-67440ebacefb.mov
=> Add object notation support for `initializeCommand`

src/spec-configuration/httpOCIRegistry.ts
ref: https://github.com/microsoft/vscode-remote-release/issues/8449
When trying to resolve a bearer token, we first attempt with the user credentials available to us for that service.  If the returned response is 401 or 403 (ghcr appears to return 403), then we attempt one more time after clearing the `Authorization` header.
In this example, I set a GitHub PAT via `docker login` and then revoked the PAT.
=> HttpOci: Retry fetching bearer token anonymously if credentials appear expired

package.json, src/spec-utils/httpRequest.ts, yarn.lock
Fixes some Component Governance and dependabot alerts.
I needed to create a fork to push up my changes because I wasn't able to get Git Credential Manager to SSO into the devcontainers org.
=> Bump proxy-agent

src/spec-node/dockerCompose.ts
fixes https://github.com/devcontainers/cli/issues/535
Similar to the in the `catch` below this change, create a new `output` object to capture docker-compose CLI logging.
For major version '1' versions of docker-compose, this change surfaces a parsing error (as described in the attached issue).
=> Capture output of docker-compose CLI

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/dockerCompose.ts, src/spec-node/dockerfileUtils.ts, src/spec-node/singleContainer.ts, src/test/configs/compose-image-with-mounts/.devcontainer/devcontainer.json, src/test/configs/compose-image-with-mounts/.devcontainer/docker-compose.yml, src/test/configs/image-with-mounts/.devcontainer/devcontainer.json, src/test/imageMetadata.test.ts
**Description**:
This PR addresses the issue when the Docker volume is named as `undefined` if the `src` argument is not specified in the `mount` command.
The issue related to the following code:
https://github.com/devcontainers/cli/blob/7de4011ca1d21781730198f718ff449c1772ebe5/src/spec-node/singleContainer.ts#L359-L364
When the `mount` command string is generated, there is no check for the `src` argument. This results in the `src` attribute being set to `undefined` when cast to a string.
To fix this behavior, we need to apply null-check for the `src` argument and don't pass it to Docker. When the `src` arg is not passed, Docker generates a random name for the volume.
**Repro sample**:
```json
{
"image": "mcr.microsoft.com/devcontainers/base:latest",
"mounts": [
{
"target": …
```
=> Rework `mount` command string generation

src/test/container-features/configs/image-with-v2-tarball/.devcontainer.json
With the release of Debian bookworm, several of the images we maintain had a major version bump from 0 to 1.  This test involving a tgz Feature tries to download via `apt` that doesn't exist in the bookworm feed.
https://github.com/devcontainers/images/commit/5366f3b9b99bf81f612bfc4c59c3030aa79a2e14
The actual issue that arises during the build is:
```
bookworm InRelease\n[2023-06-16T16:06:37.964Z] Err:5 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm Release\n  404  Not Found [IP: 40.118.250.56 443]\n[2023-06-16T16:06:38.148Z] Reading package lists...\n[2023-06-16T16:06:38.758Z] \n[2023-06-16T16:06:38.772Z] E: The repository 'https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm Release' does not have a Release …
```
=> [tests] Pin image to major version 0

src/spec-configuration/controlManifest.ts, src/spec-utils/httpRequest.ts
microsoft/vscode-remote-release#6092
=> Load NODE_EXTRA_CA_CERTS in Electron

tsconfig.base.json
Upgrade to ES2021 
Motivation
- Leverage new language features such as string.replaceAll
- ES2021 is supported on Node 15+. Node versions prior to that are already EOL.
=> Upgrade target to ES2021

package.json
With the upgrade to ES 2021 the CLI no longer support older node versions
=> Update supported node engines to ^16.13.0 || >=18.0.0

build/patch-packagejson.js, package.json, src/spec-common/cliHost.ts, src/spec-common/commonUtils.ts, src/spec-common/injectHeadless.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/featuresCLI/package.ts, src/spec-node/featuresCLI/publish.ts, src/spec-node/featuresCLI/test.ts, src/spec-node/featuresCLI/testCommandImpl.ts, src/spec-node/templatesCLI/publish.ts, src/spec-node/utils.ts, src/spec-shutdown/dockerUtils.ts, src/test/container-templates/templatesCLICommands.test.ts, src/test/testUtils.ts
https://github.com/microsoft/vscode-remote-release/issues/8698
=> Publish without node-pty dependency

package.json
=> Set npm license field to `MIT`.

CHANGELOG.md, package.json, src/spec-shutdown/dockerUtils.ts
=> Fix: Only allocate tty for `docker exec` when stdin is a tty

src/spec-node/dockerCompose.ts, src/spec-node/singleContainer.ts, src/spec-node/utils.ts
ref: https://github.com/github/codespaces/issues/15008
If a buildx build error occurs, detects if the root cause was due to a [buildx source policy](https://github.com/moby/buildkit/blob/master/docs/build-repro.md#reproducing-the-pinned-dependencies). If so, report a less generic error via the `description`.
Example with this change:
```
ERROR: failed to solve: mcr.microsoft.com/devcontainers/ruby: could not resolve image due to policy: source "docker-image://mcr.microsoft.com/devcontainers/ruby:latest" denied by policy: source denied by policy
2023-08-29 21:55:02.751Z: Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.51.1-jospicer01-1693346094254/Dockerfile-with-features -t …
```
=> Surface buildkit policy errors more clearly

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/lockfile.ts, src/spec-node/featuresCLI/resolveDependencies.ts, src/test/container-features/configs/lockfile-generate-from-empty-file-frozen/.devcontainer/devcontainer.json, src/test/container-features/configs/lockfile-generate-from-empty-file/.devcontainer/devcontainer.json, src/test/container-features/lockfile.test.ts
This change provides a way to generate a lockfile without passing the `--experimental-lockfile` flag.  
If a user want to "opt-in" to lockfiles, they may create an empty file in the expected location.  The next build of the dev container will write the lockfile information.
This is useful for Codespace users who aren't able to directly influence the flags passed to the dev container CLI.  For these users, the instructions to "opt-in" to lockfiles could be to `touch .devcontainer-lock.json` and rebuild their codespace.
Note that if the `--experimental-frozen-lockfile` flag is passed, an empty lockfile WILL be considered different and the CLI will throw an error.  
Today, providing an empty lockfile throws a JSON parsing error:
```
[1 ms] @devcontainers/cli 0.51.2. Node.js v16.20.0. linux …
```
=> Empty lockfiles will trigger lockfile to init/populate

src/spec-common/commonUtils.ts, src/spec-node/singleContainer.ts
If the container creation with `devcontainer up` command fails due to a [docker authz plugin](https://docs.docker.com/engine/extend/plugins_authorization/#access-authorization-plugin), then this change updates the CLI's failure `description` (surfacing the root cause of the failures)
=> Updates create error description to include cause for docker auth plugin errors

src/spec-configuration/containerTemplatesOCI.ts
The `options` of a feature is never validated. So therefore, if the user does not spell it out, the value is simply `undefined`.
https://github.com/devcontainers/cli/blob/71180e791b13371f8313d981dfcf06b3c8fcd2ab/src/spec-node/templatesCLI/apply.ts#L123-L129
This drops the entire feature from the intended edit.
Apply the "go" template with a feature of "git". Specifically, do not provide any `"options"` for the _git_ feature.
```shell
$ devcontainer templates apply --workspace-folder ./example-go \
-t ghcr.io/devcontainers/templates/go:latest \
-f '[{"id":"ghcr.io/devcontainers/features/git:1"}]'
```
As a result, I would expect that devcontainer.json would be generated like so.
```jsonc
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: …
```
=> template apply: Provide default feature options.

src/spec-node/dockerCompose.ts
Similar to https://github.com/devcontainers/cli/pull/656 changes for docker compose scenarios
If the container creation with devcontainer up command fails due to a [docker authz plugin](https://docs.docker.com/engine/extend/plugins_authorization/#access-authorization-plugin), then this change updates the CLI's failure description (surfacing the root cause of the failures)
=> Docker compose: Updates create error description to include cause for docker auth plugin errors

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/collectionCommonUtils/publishCommandImpl.ts, src/spec-node/featuresCLI/info.ts, src/spec-node/featuresCLI/publish.ts, src/spec-node/templatesCLI/publish.ts, src/test/container-features/configs/lockfile-outdated-command/.devcontainer.json, src/test/container-features/containerFeaturesOCIPush.test.ts, src/test/container-features/featuresCLICommands.test.ts, src/test/container-features/lockfile.test.ts
Ref: https://github.com/devcontainers/cli/issues/676
Reported in https://github.com/devcontainers/spec/discussions/327
Previously the comparision done to sort versions would incorrectly place patch versions >=10 above versions x.x.2-x.x.9.  This is due to the versions seemingly being sorted as string.
Eg:
Note that `1.0.11` is not the final entry.
=> fix version sorting and report major version in `outdated`

src/spec-configuration/lockfile.ts, src/spec-node/upgradeCommand.ts, src/test/container-features/lockfile.test.ts
ref: https://github.com/github/codespaces/issues/15791
Adds a `--dry-run` flag to the upgrade command, printing the generated lockfile to standard out instead of the default of writing lockfile to disk.
I think this may be useful for dependabot and more generally I think it could be useful to users.
=> add `--dry-run` to upgrade command

src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-configuration/lockfile.ts, src/spec-node/upgradeCommand.ts, src/test/container-features/configs/lockfile-upgrade-feature/.gitignore, src/test/container-features/configs/lockfile-upgrade-feature/expected.devcontainer.json, src/test/container-features/configs/lockfile-upgrade-feature/input.devcontainer.json, src/test/container-features/lockfile.test.ts
This change adds new arguments to the `upgrade` command to facilitate updating a single Feature in a `devcontainer.json`.  After the edit to the `devcontainer.json` is made, the lockfile is updated according to the requirements (version tags) of each Feature. 
https://github.com/devcontainers/cli/assets/23246594/68073ae6-3590-4c6a-9193-edeed5dd7883
This is useful in dependbot's [`file_updater`](https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/file_updaters/README.md) step, allowing us to do shell out to the CLI directly for this operation. This is similar to the [Swift's `file_updater` implementation in dependabot core](https://github.com/joshspicer/dependabot-core/blob/joshspicer/devcontainers/swift/lib/dependabot/swift/file_updater/lockfile_updater.rb#L37) …
=> Edit a Feature pinned version via upgrade cmd

src/spec-node/utils.ts
I was testing detection of buildx source policy errors (see https://github.com/devcontainers/cli/pull/627), and noticed the error message has changed in 0.12.x.  I haven't seen a better form of detection yet (+ asked the author a while back).
=> update string in `isBuildKitImagePolicyError`

src/spec-common/injectHeadless.ts, src/spec-node/containerFeatures.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/imageMetadata.ts, src/test/dockerfileUtils.test.ts
Unblocks bug with `#syntax` directives + buildkit + user namespace remapping by not auto-injecting the `#syntax` directive in the extended (Features) intermediate Dockerfile, and ignoring user-contributed syntax directives.  
See https://github.com/moby/buildkit/issues/4556 for more info.
Enable with hidden `--omit-syntax-directive` `up` and `build` flag.  **This flag will be removed once upstream is fixed.**
ref: https://github.com/github/codespaces/issues/15748
=> Add hidden `--omit-syntax-directive` flag

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerFeaturesConfiguration.ts, src/test/container-features/configs/lockfile-outdated-command/.devcontainer.json, src/test/container-features/lockfile.test.ts, src/test/container-templates/containerTemplatesOCI.test.ts
Made a couple changes to the `outdated` command.
- Addresses https://github.com/devcontainers/cli/issues/712 by omitting the deprecated "short-hand" Feature syntax from the output of `outdated`.  
- This is a bit opinionated, but my reasoning here is that - since there is no way for the user to alter these Feature versions (they're "held back" to the major version from when they were deprecated) - it doesn't make sense to surface in `outdated`.  
- Omitting these Features from `outdated` will subsequently cause the [dependabot integration](https://github.com/dependabot/dependabot-core/blob/main/devcontainers/lib/dependabot/devcontainers/file_parser/feature_dependency_parser.rb#L47) to not consider them for version updates, which [is already being done as an exceptional …
=> Ignore non-versioned Features when generating `outdated` report

src/spec-utils/httpRequest.ts
`follow-redirects` [npm doc](https://www.npmjs.com/package/follow-redirects) states that it's a drop-in replacement for the native http and https modules, but it turns out that's not quite true as it additionally sets a maximum HTTP request body length of 10MB by default.  I expect this is because the request body is cached internally so it can be replayed, so is done in order to manage memory usage.
This overrides the default maxBodySize to 100MB as a quick fix to allow larger devcontainer features to be published with the CLI.  Without this, some more expensive solution like chunking would be required.
Fixes #270
=> Set maxBodyLength to 100MB to allow larger feature uploads

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, example-usage/workspace/.devcontainer/Dockerfile, example-usage/workspace/.devcontainer/devcontainer.json, src/test/configs/compose-Dockerfile-with-features/.devcontainer/Dockerfile, src/test/configs/compose-Dockerfile-with-features/.devcontainer/devcontainer.json, src/test/configs/compose-Dockerfile-with-features/.devcontainer/docker-compose.yml, src/test/configs/compose-Dockerfile-with-target/.devcontainer/Dockerfile, src/test/configs/compose-Dockerfile-with-target/.devcontainer/devcontainer.json, src/test/configs/compose-Dockerfile-with-target/.devcontainer/docker-compose.yml, src/test/configs/compose-image-with-features/.devcontainer/devcontainer.json, src/test/configs/compose-image-with-features/.devcontainer/docker-compose.yml, src/test/configs/dockerfile-with-features/.devcontainer.json, src/test/configs/dockerfile-with-features/Dockerfile, src/test/configs/dockerfile-with-syntax/.devcontainer.json, src/test/configs/dockerfile-with-syntax/Dockerfile, src/test/configs/dockerfile-with-target/.devcontainer.json, src/test/configs/dockerfile-with-target/Dockerfile, src/test/configs/image-with-features/.devcontainer.json, src/test/container-features/configs/dockerfile-with-v2-oci-features/.devcontainer.json, src/test/container-features/configs/dockerfile-with-v2-oci-features/Dockerfile, src/test/container-features/configs/image-with-v2-tarball/.devcontainer.json, yarn.lock
- Removing dependency on `ip` package to address https://github.com/advisories/GHSA-78xj-cgh5-2h22.
- Fixing tests to make `docker-in-docker` work again.
=> Remove dependency on ip package

.github/workflows/dev-containers.yml, src/spec-common/cliHost.ts, src/spec-common/commonUtils.ts, src/spec-configuration/containerCollectionsOCI.ts, src/spec-node/configContainer.ts, src/spec-node/containerFeatures.ts, src/spec-node/devContainers.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/dockerCompose.ts, src/spec-node/imageMetadata.ts, src/spec-node/upgradeCommand.ts, src/spec-node/utils.ts, src/spec-shutdown/dockerUtils.ts, src/test/cli.build.test.ts, src/test/configs/updateUIDamd64-platform-option/.devcontainer.json, src/test/configs/updateUIDamd64-platform-option/Dockerfile, src/test/configs/updateUIDamd64/.devcontainer.json, src/test/configs/updateUIDamd64/Dockerfile, src/test/configs/updateUIDarm64-platform-option/.devcontainer.json, src/test/configs/updateUIDarm64-platform-option/Dockerfile, src/test/configs/updateUIDarm64/.devcontainer.json, src/test/configs/updateUIDarm64/Dockerfile, src/test/configs/updateUIDarm64v8-platform-option/.devcontainer.json, src/test/configs/updateUIDarm64v8-platform-option/Dockerfile, src/test/configs/updateUIDarm64v8/.devcontainer.json, src/test/configs/updateUIDarm64v8/Dockerfile, src/test/dockerUtils.test.ts, src/test/dockerfileUtils.test.ts, src/test/testUtils.ts, src/test/updateUID.test.ts
If the user changes the platform to a non-native arch as suggested [here](https://github.com/microsoft/vscode-remote-release/issues/7779#issuecomment-1375375743), the devcontainers CLI fails to launch due to attempting to load the wrong platform during the "updateUID" image build.
Opening as a draft PR to show the behavior. Will follow up with a fix once I figure out where it should go.
=> [FIX] Don't crash updating UID/GID when the image's platform is different from the native CPU arch

CHANGELOG.md, package.json, src/spec-node/containerFeatures.ts, src/spec-node/devContainersSpecCLI.ts, src/spec-node/singleContainer.ts, src/test/cli.build.test.ts
This makes tagging part of the build command to avoid https://github.com/devcontainers/ci/issues/271.
=> Add tags with build command

src/spec-node/containerFeatures.ts
I am trying to use the new `--cache-to` feature from #570 with a [registry cache](https://docs.docker.com/build/cache/backends/registry/).
If I understand it correctly this only works when using both `--cache-to` and `--cache-from`, but the devcontainers-cli does not send `--cache-from` to `docker buildx build`.
=> Fix: propagate --cache-from to buildx build

src/spec-node/containerFeatures.ts, src/test/cli.build.test.ts
Add `--no-cache` arg to the docker build command that extends the base image with the feature images when `--build-no-cache` is passed.
The build will always use a cached feature image if it has one. This was making it impossible to replicate a problem in our CI process caused by [this issue](https://github.com/Azure/azure-cli/issues/28676). Our CI pipeline was failing to install the Azure CLI, but building locally worked fine. The CI pipeline uses GitHub actions, so no cache of the build was available, however, I had cached versions of the image locally and passing the `--build-no-cache` continued to use the cache. I had to remove all the images via `docker images -q "vsc-$MY_IMAGE*" | xargs docker rmi -f` order to get a build representative of my CI environment working locally.
Closes …
=> Disable cache on feature build when `--build-no-cache` is passed

src/spec-node/dockerCompose.ts
This commit adds a UUID to the filename for `docker-compose.devcontainer.containerFeatures`.
The current filename uses a timestamp to avoid collisions, which causes different invocations of the CLI to overwrite each others files.
We hit this because our end to end tests invoke the cli, and they run in parallel via go's `t.Parallel()`.
=> Stop races docker-compose.devcontainer.containerFeatures file

src/spec-node/devContainersSpecCLI.ts, src/spec-node/dockerCompose.ts, src/test/cli.up.test.ts, src/test/configs/compose-with-name/.devcontainer/devcontainer.json, src/test/configs/compose-with-name/.devcontainer/docker-compose.yml
microsoft/vscode-remote-release#512
=> Support project name attribute

src/spec-configuration/containerFeaturesConfiguration.ts, src/test/cli.build.test.ts, src/test/configs/image-with-local-feature/.devcontainer.json
[Issue 834](https://github.com/devcontainers/cli/pull/838)
Confusing error message modified to more understandable message.
=> obtuse and confusing error with local feature under WSL #834

src/spec-node/devContainersSpecCLI.ts, src/spec-node/templatesCLI/metadata.ts, src/test/container-templates/templatesCLICommands.test.ts
Follow up to https://github.com/devcontainers/cli/pull/865.  Exposes Template metadata cached on a manifest with the `templates metadata` subcommand
Also relevant for https://github.com/microsoft/vscode-remote-release/issues/10095, by allowing tools to query the metadata of a Template before downloading its contents.
=> add 'templates metadata' subcommand

src/spec-configuration/containerCollectionsOCI.ts, src/spec-configuration/containerTemplatesOCI.ts, src/spec-node/templatesCLI/apply.ts, src/test/container-templates/containerTemplatesOCI.test.ts
Related: https://github.com/devcontainers/spec/pull/484, https://github.com/microsoft/vscode-remote-release/issues/10095
The `templates apply` command now exposes a flag `--omit-paths`.  Following the same file/folder syntax as shown in https://github.com/devcontainers/spec/pull/484, the provided array of paths will not be extracts from the tarball when applying a Template.
Expanded upon `getBlob()`'s existing filtering logic.
=> Add `--omit-paths` flag to `templates apply`

src/spec-configuration/httpOCIRegistry.ts
Some OCI registries return a mangled WWW-Authenticate header. For example, versions of Sonatype Nexus Repository Manager return:
```http
WWW-Authenticate: BASIC realm="..."
```
The current handling of the WWW-Authenticate header leaves the CLI to error when pushing to these registries. This commit adds more leniency and accepts weirdly capitalised versions of the header also.
=> Add more leniency towards registries that malform WWW-Authenticate.

src/spec-node/featuresCLI/utils.ts
Function `checkMultiple` which is available in `dev-container-features-test-lib` (test library script) doesn't work as intended
It exits while looping through the 1st command. For example, execution of this script:
```bash
#!/bin/bash
set -e
source dev-container-features-test-lib
checkMultiple "Test multiple" 2 "echo First" "echo Second"
```
Results in error: 
It seems that it's caused by the way how the `PASSED` variable is incremented: `((PASSED++))` - The value is returned first, then `PASSED` is incremented
For the first iteration the value of the expression is 0, so the return status is set to 1
> (( expression ))
> If the value of the expression is non-zero, the return status is 0; otherwise the return status is 1.
> https://www.gnu.org/software/bash/manual/bash.html#Conditional-Cons …
=> fix: change increment syntax in test library script

src/spec-node/templatesCLI/publish.ts
As shown in https://github.com/devcontainers/spec/discussions/513, this log message is not relevant and masking the true error printed just before.
=> Remove unnecessary log

src/spec-configuration/lockfile.ts, src/spec-node/featuresCLI/resolveDependencies.ts
ref: #895 
**Description**
* The pr is raised as a solution to the issue `TypeError: Cannot read properties of undefined (reading 'fsPath')` #895.
=> solution to cli issue - TypeError: Cannot read properties of undefined (reading 'fsPath') #895

CHANGELOG.md, package.json, src/spec-common/injectHeadless.ts, src/test/getHomeFolder.test.ts
microsoft/vscode-remote-release#10707
=> Ignore non-writeable HOME

src/spec-common/injectHeadless.ts
Just fixing a typo in `src/spec-common/injectHeadless.ts`.
=> Typo: Envrionment -> Environment

CHANGELOG.md, package.json, src/spec-configuration/containerCollectionsOCI.ts
microsoft/vscode-remote-release#11046
=> Redirect devcontainers-contrib to devcontainers-extra

.github/workflows/dev-containers.yml, CHANGELOG.md, package.json, src/spec-configuration/containerFeaturesConfiguration.ts, src/spec-node/containerFeatures.ts, src/spec-node/dockerCompose.ts, src/spec-node/singleContainer.ts, src/test/cli.podman.test.ts
microsoft/vscode-remote-release#10585
=> Podman: Use label=disable instead of z flag
